version: '3.8'

services:
  db:
    image: postgres:16
    container_name: graphapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-graphapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-graphapppassword}
      POSTGRES_DB: ${POSTGRES_DB:-graphappdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-graphapp}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: graphapp-api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
