"""Initial migration

Revision ID: 2e2be1122068
Revises: 
Create Date: 2025-08-18 15:18:23.912339+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg
import uuid
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '2e2be1122068'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create entities table
    op.create_table('entities',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('entity_metadata', pg.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_type', 'entities', ['type'])
    op.create_index('ix_entities_name', 'entities', ['name'])
    op.create_index('ix_entities_metadata_gin', 'entities', ['entity_metadata'], postgresql_using='gin')
    
    # Create relationships table
    op.create_table('relationships',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
        sa.Column('source_entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('target_entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('relationship_metadata', pg.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'type', name='uq_relationships_source_target_type')
    )
    op.create_index('ix_relationships_source_entity_id', 'relationships', ['source_entity_id'])
    op.create_index('ix_relationships_target_entity_id', 'relationships', ['target_entity_id'])
    op.create_index('ix_relationships_type', 'relationships', ['type'])
    op.create_index('ix_relationships_metadata_gin', 'relationships', ['relationship_metadata'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationships_metadata_gin', table_name='relationships')
    op.drop_index('ix_relationships_type', table_name='relationships')
    op.drop_index('ix_relationships_target_entity_id', table_name='relationships')
    op.drop_index('ix_relationships_source_entity_id', table_name='relationships')
    op.drop_table('relationships')
    
    op.drop_index('ix_entities_metadata_gin', table_name='entities')
    op.drop_index('ix_entities_name', table_name='entities')
    op.drop_index('ix_entities_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
